//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PC_XXEntities : DbContext
    {
        public PC_XXEntities()
            : base("name=PC_XXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CleaningRoom> CleaningRoom { get; set; }
        public virtual DbSet<CleaningRoomDetail> CleaningRoomDetail { get; set; }
        public virtual DbSet<CleaningRoomItem> CleaningRoomItem { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemStatus> ItemStatus { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<ReservationCheckOut> ReservationCheckOut { get; set; }
        public virtual DbSet<ReservationRequestItem> ReservationRequestItem { get; set; }
        public virtual DbSet<ReservationRoom> ReservationRoom { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<RoomType> RoomType { get; set; }
    }
}
