//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservationRoom()
        {
            this.ReservationCheckOut = new HashSet<ReservationCheckOut>();
            this.ReservationRequestItem = new HashSet<ReservationRequestItem>();
        }
    
        public int ID { get; set; }
        public int ReservationID { get; set; }
        public int RoomID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public int DurationNights { get; set; }
        public int RoomPrice { get; set; }
        public Nullable<System.DateTime> CheckInDateTime { get; set; }
        public Nullable<System.DateTime> CheckOutDateTime { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationCheckOut> ReservationCheckOut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationRequestItem> ReservationRequestItem { get; set; }
        public virtual Room Room { get; set; }
    }
}
